illinois-ceesd/mirgecom

.github/workflows/tests.yaml
Addresses https://github.com/illinois-ceesd/planning/issues/51
=> Add Flake8 integration in CI

.github/workflows/tests.yaml, mirgecom/wave.py, test/test_wave.py
Closes #4 
I found and fixed the bug that was causing inconsistency between the cosine test and the manufactured test. Now each test requires a `-1` factor in the RHS for both `u` and `v`. My algebra and implementation also now appear to agree with what I get from `sympy`.
Looks ready for review. One unresolved question: should it be merged with the tests passing (i.e., with fudge factor) or failing (without fudge factor)?
=> Add unit tests

examples/wave-eager.py, mirgecom/euler.py, mirgecom/wave.py
=> Remove 'Remove grudge dependence?'

.github/workflows/flake8.yaml, .github/workflows/tests.yaml
=> Separate Flake8 test

mirgecom/wave.py, test/test_wave.py
Adds stability check to wave tests as requested in #15.
=> Wave test stability check

setup.cfg
Fixes https://github.com/illinois-ceesd/planning/issues/51
=> Adjust PEP8 ignores

mirgecom/symbolic.py, mirgecom/wave.py, requirements.txt, test/test_wave.py
=> Array context

mirgecom/eos.py, mirgecom/steppers.py, test/test_euler.py, test/test_init.py
If you're trying to run this at home, note that this relies on:
- https://github.com/inducer/meshmode/pull/22
- https://github.com/inducer/grudge/pull/10
=> Fix euler array context

.github/workflows/tests.yaml, examples/run_examples.sh
I would like to add this examples runner script so that teesd can expect its presence regardless of branch.
=> Add example runner script

examples/wave-eager-mpi.py, requirements.txt
Fixes #41.
Mostly a copy of https://github.com/inducer/grudge/blob/master/examples/wave/wave-eager-mpi.py
=> Add wave-eager-mpi

mirgecom/wave.py
https://github.com/inducer/grudge/pull/15/commits/687a28bf850d168bb1109f2b78ebf3a844853feb shows some embarrassing brain damage being fixed in grudge. This PR fixes the fallout from that for the wave operator. The Euler-related fixes will go into #77.
=> Fix wave operator for https://github.com/inducer/grudge/pull/15

doc/running.rst
This is how it looks like rendered: https://mirgecom.readthedocs.io/en/doc_run/running.html#running-on-specific-systems
=> doc: add run instructions for quartz/lassen

doc/support.rst, examples/hello-world-mpi.py, examples/lump-mpi.py, examples/run_examples.sh, examples/sod-mpi.py, examples/vortex-mpi.py, examples/wave-eager-mpi.py, mirgecom/__init__.py, mirgecom/mpi.py
Makes it a little more explicit where `MPI_Init()` should occur.
Fixes #105
=> Add mpi_entry_point decorator

.rtd-env-py3.yml, requirements.txt
cf. https://github.com/illinois-ceesd/emirge/pull/28
=> Remove islpy from dev packages

mirgecom/euler.py, mirgecom/symbolic.py, mirgecom/wave.py, test/test_wave.py
Pulled a few things out of the heat PR so I can keep it more heat focused (and so I can squash it later).
=> Misc. fixes from heat equation PR

doc/faq.rst
Depends on https://github.com/illinois-ceesd/emirge/pull/83
=> doc: record/replay python package versions

.github/workflows/ci.yaml
=> Fix double CI

doc/faq.rst
Needs https://github.com/illinois-ceesd/emirge/pull/91
=> doc: record/replay conda env

examples/pulse-mpi.py, mirgecom/mpi.py
=> Disable mprobe to avoid MPI crash on multiple nodes

doc/development.rst
https://mirgecom.readthedocs.io/en/doc-install/development.html
=> doc: installation

doc/development.rst
here is how it looks like rendered: https://mirgecom.readthedocs.io/en/doc-pr/development.html
=> doc: add pull request docs

doc/development.rst
Rendered HTML is here: https://mirgecom.readthedocs.io/en/doc-packages/development.html
=> doc: document packages

requirements.txt
https://blog.python.org/2020/11/pip-20-3-release-new-resolver.html
🙉 🙈 🙊
=> Fix novel pip breakage

doc/running.rst, examples/lassen.bsub.sh, examples/quartz.sbatch.sh
https://mirgecom.readthedocs.io/en/doc-opencl/running.html#opencl-device-selection
=> doc: explain OpenCL device selection and add to examples

.github/workflows/ci.yaml, .rtd-env-py3.yml, doc/conf.py, doc/development.rst, doc/index.rst
Rendered: https://mirgecom.readthedocs.io/en/furo/
=> switch doc to furo theme

.gitignore, examples/wave-eager-mpi.py, examples/y0euler_restart.py
This adds an experimental restart capability to the Y0 driver.  Note the use of the `my_checkpoint` function in the driver that allows the user to add functionality to the checkpointing. 
edit: Sorry for the deep diff.  This PR also merged int current master and @inducer's restart pilot.  The relevant bits are [where it reads](https://github.com/illinois-ceesd/mirgecom/pull/178/files#r543886682), and [where it writes](https://github.com/illinois-ceesd/mirgecom/pull/178/files#r543885774).
=> Y0 restart

doc/development/pullrequests.rst
This doesn't run pylint cause that takes a long time.
=> add example git commit hook to run flake8/pydocstyle

mirgecom/profiling.py
Also adds totals for num_calls and time.
Mostly extracted from #96.
=> profiling: add pyopencl.Array elementwise kernels

doc/faq/errors.rst, doc/faq/faq.rst
rendered docs are here: https://mirgecom.readthedocs.io/en/doc-platform_not_found_khr/faq/errors.html
=> doc: add documentation about PLATFORM_NOT_FOUND_KHR

mirgecom/boundary.py, mirgecom/euler.py, mirgecom/initializers.py, test/test_euler.py, test/test_init.py
This is a modification to the scalar advection #95 feature that renames the CV component cv.mass_fractions --> cv.scalar.
=> Rename cv.mass_fractions --> cv.species_mass

requirements_dev.txt
(feel free to suggest additional packages)
=> add requirements_dev.txt file

examples/heat-source-mpi.py, mirgecom/diffusion.py, requirements.txt, test/test_diffusion.py
Depends on #156 and inducer/grudge#37.
=> Add variable diffusivity to diffusion_operator

examples/heat-source-mpi.py, mirgecom/diffusion.py
Adds leftover suggestions from variable diffusivity PR (#180).
=> Add leftover diffusion suggestions from #180

examples/pulse-mpi.py
=> pulse-mpi: add missing memory pool

doc/development/pullrequests.rst
=> doc: add PR review resources

mirgecom/simutil.py
This change allows driver writers to add custom grid-supported fields to their viz files.
=> Allow visualization of custom fields.

.github/workflows/ci.yaml
We could change the "normal" CI tests to use emirge too, but I would like to observe how this behaves for a week or so before doing that change.
=> ci: test emirge install

mirgecom/integrators.py
Add an euler explicit time stepper to mirgecom.
=> added explicit euler timestepper

requirements.txt
Complements https://github.com/illinois-ceesd/emirge/pull/113
=> annotate dev packages with --editable

requirements.txt
Used for various logging functionality (memory usage, startup time)
=> require psutil

.github/workflows/ci.yaml, README.md, doc/development/packages.rst, doc/development/pullrequests.rst, doc/running/systems.rst
=> Rename  master branch to main

.ci-support/install.sh, examples/lump-mpi.py, examples/pulse-mpi.py, examples/scalar-lump-mpi.py, examples/sod-mpi.py, examples/vortex-mpi.py, mirgecom/simutil.py
=> Rename parallel mesh widget

examples/lassen.bsub.sh
Fixes error of the type:
CUDA_ERROR_FILE_NOT_FOUND: file not found
Fixes #292
=> set pocl cache dir

mirgecom/fluid.py, test/test_euler.py
Does exactly what the title says :smile:
=> Remove deprecated object alias and "interp" function

.ci-support/install.sh, .github/workflows/ci.yaml, requirements.txt
~~❗ **Before merging, undo the changes to requirements.txt**❗~~
=> fix CI runs

.github/workflows/ci.yaml
Needs https://github.com/illinois-ceesd/emirge/pull/126
=> skip clone on CI

mirgecom/diffusion.py
=> Fix diffusion_operator docstring

mirgecom/fluid.py
Start on and discuss better documentation for fluid data handling in *MIRGE-Com*.
=> Update doc for ConservedVars dataclass

mirgecom/fluid.py
=> Update doc for ConservedVars dataclass after @majosm review

doc/support/filter.rst, doc/support/support.rst, mirgecom/filter.py, test/test_euler.py, test/test_filter.py
This PR revives all the hard work by @MTCam in #92 (and also supersedes #92). Uses some recent functionality in meshmode and grudge.
=> Add modal filtering capability to Mirgecom

mirgecom/euler.py
Fix bug in euler operator with respect to boundary arguments.
=> Pass time to boundary call

doc/discretization.rst, doc/fluid.rst, doc/index.rst, doc/model/model.rst
Targets #345.
This shuffles the doc sectioning a bit. @MTCam Look OK? Merge away if so.
=> Reshuffle fluid model/discr doc sections

examples/wave-eager-mpi.py, examples/wave-eager.py
This PR addresses the problems we discussed today at the dev meeting.
The problem related to getting `-inf` in the temperature calculations is fixed in this grudge PR: https://github.com/inducer/grudge/pull/105
A forthcoming PR will add a callback routine to check for NaNs/blowup.
Other than that, the simulations appear to be okay.
=> Fix wave examples

.github/workflows/ci.yaml
Should resolve spurious CI failures.
=> ci: update packages

doc/conf.py, examples/README.md
Add readme to examples dir with minimal detail.  Hopefully help in effort to thin down the examples and improve CI turn-around.
cc: @thomasgibson
=> Add examples readme

mirgecom/eos.py, mirgecom/fluid.py
Cache some of the expensive calculations with CV.  This adds temperature and pressure only. Initial tests show significant performance impacts for eager mode.
=> Memoize dv

doc/support/arrays.rst
=> Fix doctest for updated pyopencl error message

mirgecom/filter.py, mirgecom/mechanisms/__init__.py
=> Address pylint failures resulting from actx/meshmode FEM transform shuffle

.github/workflows/ci.yaml, .gitignore, mirgecom/filter.py, run-mypy.sh, run-pylint.sh
=> add lint scripts

test/test_euler.py
=> Eliminate stateful, in-place style in inviscid flux test.

.ci-support/production-driver-setup.sh, .ci-support/production-setup.sh, .github/workflows/ci.yaml
Sorry - addition of Y1 tests could not have been tested in main until merge.  This should fix them.  When there are no changes to apply - skip trying to apply changes.
=> Update Y1 CI testing so that it also working in main.

.ci-support/.gitattributes, .ci-support/production-driver-setup.sh, .ci-support/production-setup.sh, .github/workflows/ci.yaml, examples/autoignition-mpi.py, examples/lump-mpi.py, examples/mixture-mpi.py, examples/nsmix-mpi.py, examples/poiseuille-mpi.py, examples/pulse-mpi.py, examples/run_examples.sh, examples/scalar-lump-mpi.py, examples/sod-mpi.py, examples/vortex-mpi.py, examples/wave-eager-mpi.py, examples/wave-eager.py, mirgecom/boundary.py, mirgecom/fluid.py, mirgecom/flux.py, mirgecom/initializers.py, mirgecom/inviscid.py, mirgecom/simutil.py, mirgecom/steppers.py, mirgecom/viscous.py, test/test_euler.py, test/test_init.py, test/test_viscous.py
Co-authored-by: Matthias Diener <mdiener@illinois.edu>
=> Update from Y1 downstream

.ci-support/production-testing-env.sh, examples/autoignition-mpi.py, examples/heat-source-mpi.py, examples/lump-mpi.py, examples/mixture-mpi.py, examples/pulse-mpi.py, examples/scalar-lump-mpi.py, examples/sod-mpi.py, examples/vortex-mpi.py, examples/wave-eager-mpi.py, examples/wave-mpi.py
=> Update lazy examples to match production versions

examples/autoignition-mpi.py, examples/heat-source-mpi.py, examples/lump-mpi.py, examples/mixture-mpi.py, examples/pulse-mpi.py, examples/run_examples.sh, examples/scalar-lump-mpi.py, examples/vortex-mpi.py
This change set moves the examples closer to production, makes them lazy-ready, and updates the runner so that it can optionally run examples in lazy mode.
=> Laxify the examples

examples/sod-mpi.py
Somehow missed this one in #446.
=> Add lazy-compatible Sods shock example

.ci-support/production-driver-install.sh, .ci-support/production-testing-env.sh, .github/workflows/ci.yaml
This allows us to add an arbitrary number of production driver tests, defaults = nozzle & isolator.
=> Add support for testing multiple production drivers.

.ci-support/production-testing-env.sh, .github/workflows/ci.yaml, bin/mirgecompare.py, examples/compare_lazy_solution.sh, examples/test_lazy_accuracy.sh, requirements.txt
=> add mirgecompare script

mirgecom/simutil.py
Add support to write viz files at user-selected path; missed it in the port from production.  The production drivers use this.
=> Restore vizfile directory handling

.github/workflows/ci.yaml
=> Time the tests

mirgecom/initializers.py
Catches mistakes like the one I made here: https://github.com/illinois-ceesd/mirgecom/pull/452/commits/f91e99c4ae48e7a8a8eef0c50f08b67629647e4a
=> Check that species inputs in MulticomponentLump are consistent even when nspecies == 0

test/test_lazy.py
I fIxed the inconsistent BC in the multicomponent lump case (which I forgot about in #452). This caused the error computation to fail, because the RHS became all 0s in some components. So I tweaked the implementation to mimic `math.isclose`. I also added a second Euler test case that exercises the components that became 0 in the original case.
=> Tweak lazy operator tests

requirements.txt
(required by nozzle, among others)
=> add pyyaml to requirements.txt

mirgecom/transport.py
Address @thomasgibson review comments to transport API.
=> Undumben the function name for volume viscosity

examples/heat-source-mpi.py, examples/lump-mpi.py, examples/scalar-lump-mpi.py, examples/wave-mpi.py, examples/wave.py
cc: @matthiasdiener 
Note this merges to `more_lazy`, *not* `main`.
=> Speeds up the examples - lazy examples run in reasonable time

.gitignore, requirements_dev.txt
Adds a few useful packages for MIRGE development and ignores temporary files created by emacs editors
=> Add some more useful stuff to dev env

test/test_operators.py
Context: https://github.com/illinois-ceesd/mirgecom/pull/466#discussion_r690518790
=> Re-implement _coord_test_func symbolically

mirgecom/viscous.py, test/test_viscous.py
(Also fixed up tests so they exercise the array-valued diffusivity branch of the function.)
I'm told that doing it this way is easier for lazy to work with.
=> Simplify `get_local_max_species_diffusivity`

mirgecom/flux.py
Add a general LFR flux reconstruction function
=> Add generic LLF flux reconstruction

test/test_operators.py
Changes all of the `*_test_func` functions to return symbolic expressions and moves the evaluation part inside the gradient test. As a result, the test functions don't need to optionally compute and return the gradient; the test itself can compute it from the symbolic expressions.
=> Move symbolic evaluation inside `test_grad_operator`

mirgecom/steppers.py
Looks like the code for this was removed in #220, and no one has since complained (?), so I think that means it's safe to fully remove. 🙂
=> Remove unused `get_timestep` argument from steppers

mirgecom/steppers.py, test/test_time_integrators.py
=> Add #530 to production

.ci-support/production-drivers-install.sh
=> Update isolator production driver to main branch

.ci-support/production-drivers-install.sh
=> Reset flame1d production CI back to main

doc/conf.py, mirgecom/simutil.py, mirgecom/symbolic.py
=> Avoid using isinstance(..., Number) to detect scalars

test/test_diffusion.py
Seems like it works?
cc @dshtey2
=> Add tests for nonlinear diffusion

examples/autoignition-mpi.py
(not adding to CI since compilation is slow)
=> autoignition: make it lazy

.ci-support/merge-install-production-branch.sh
=> Switch production testing to production branch

conda-env.yml
=> add a few more dev tools

.ci-support/production-testing-env.sh, conda-env.yml, mirgecom/euler.py, mirgecom/filter.py, mirgecom/fluid.py, mirgecom/navierstokes.py, mirgecom/simutil.py, test/test_bc.py, test/test_eos.py, test/test_euler.py, test/test_filter.py, test/test_fluid.py, test/test_lazy.py, test/test_operators.py, test/test_restart.py, test/test_simutil.py, test/test_viscous.py
=> Dispatch join calls

mirgecom/flux.py, mirgecom/inviscid.py, test/test_flux.py
Add hll riemann approximate flux 
Add testing of numerical flux functions (rusanov and hll)
=> add support for hll riemann numerical flux

examples/pulse-mpi.py
Previously, all examples were 2D by default, thus not checking 3D
in CI e.g.
=> Pulse: make it 3D by default

conda-env.yml, mirgecom/mpi.py
=> add possibility to debug multi-rank mirgecom with pudb

conda-env.yml, mirgecom/mpi.py
=> prepend rank number to all print() invocations

.ci-support/production-drivers-install.sh, .ci-support/production-testing-env.sh, examples/autoignition-mpi.py, examples/doublemach-mpi.py, examples/heat-source-mpi.py, examples/hotplate-mpi.py, examples/lump-mpi.py, examples/mixture-mpi.py, examples/nsmix-mpi.py, examples/poiseuille-mpi.py, examples/pulse-mpi.py, examples/scalar-lump-mpi.py, examples/sod-mpi.py, examples/vortex-mpi.py, mirgecom/boundary.py, mirgecom/diffusion.py, mirgecom/eos.py, requirements.txt, test/test_bc.py
=> Production+distributed parallel lazy

.ci-support/production-testing-env.sh, examples/autoignition-mpi.py, examples/heat-source-mpi.py, examples/lump-mpi.py, examples/mixture-mpi.py, examples/pulse-mpi.py, examples/scalar-lump-mpi.py, examples/sod-mpi.py, examples/vortex-mpi.py, mirgecom/euler.py
The main thing this does is use the correct/latest MPI-enabled array context in the examples.  Once merged with #562, production env customization will go away.
=> Update examples and testing env to match production

.github/workflows/ci.yaml, conda-env.yml
=> add pylint

.ci-support/production-drivers-install.sh, .ci-support/production-testing-env.sh, examples/autoignition-mpi.py, examples/heat-source-mpi.py, examples/lump-mpi.py, examples/mixture-mpi.py, examples/pulse-mpi.py, examples/scalar-lump-mpi.py, examples/sod-mpi.py, examples/vortex-mpi.py, examples/wave-mpi.py, mirgecom/diffusion.py, mirgecom/euler.py, mirgecom/wave.py, requirements.txt
cc: #467 #556
Needs:
---
To install/run via emirge:
```
$ ./install.sh --branch=distributed-parallel-lazy
[...]
$ mpirun -n 2 python -m mpi4py examples/wave-mpi.py --lazy
```
=> Distributed+device-parallel lazy

doc/faq/errors.rst
=> doc: add OUT_OF_RESOURCES error

examples/autoignition-mpi.py, examples/heat-source-mpi.py, examples/lump-mpi.py, examples/mixture-mpi.py, examples/pulse-mpi.py, examples/scalar-lump-mpi.py, examples/sod-mpi.py, examples/vortex-mpi.py, examples/wave-mpi.py, examples/wave.py
=> examples: use memory allocator in lazy mode

mirgecom/navierstokes.py, test/test_lazy.py
Production counterpart to #631.
=> Standalone NS gradients (production)

mirgecom/navierstokes.py, test/test_lazy.py
Splits CV gradient and temperature gradient computations into standalone functions so that they can be called outside of NS.
=> Standalone NS gradients

examples/heat-source-mpi.py, mirgecom/diffusion.py, test/test_diffusion.py, test/test_lazy.py
Applies some updates to `diffusion_operator` originating from the multi-physics work.
=> Modernize `diffusion_operator`

doc/faq/errors.rst, doc/faq/install.rst
=> doc: add info on installing system ICDs

.github/workflows/ci.yaml, bin/mirgecompare.py
=> Mirgecompare flake8

test/test_filter.py
=> Use context-specific comparison.

.github/workflows/ci.yaml
=> fix doc build

.ci-support/production-testing-env.sh, test/test_symbolic.py
Forgot to set this back before merging. 😞 
=> Reset production branch in CI (+ fix bug)

.ci-support/install.sh, .github/workflows/ci.yaml, examples/pulse-mpi.py, examples/run_examples.sh, examples/scripts/run_gpus_generic.sh
https://github.com/illinois-ceesd/planning/wiki/Porter-CI
=> Run examples on porter

.github/workflows/ci.yaml, .rtd-env-py3.yml, conda-env.yml
=> remove vtk from default install

.ci-support/production-testing-env.sh
=> Re-comment  production env customization

mirgecom/symbolic.py, test/test_operators.py
Missed a couple of things in #619.
~~:warning: Set production branch back before merging :warning:~~
=> Symbolic array container support fixes

bin/mirgecompare.py
=> Check for valid file and file path in mirgecompare

setup.cfg
`flake8-bugbear` v22.7.1 appears to be producing spurious `B023` errors for a bunch of code in the tests, e.g.:
```
test/test_bc.py:162:42: B023 Function definition does not bind loop variable 'discr'.
return actx.to_numpy(op.norm(discr, vec, p=np.inf, dd=BTAG_ALL))
^
test/test_viscous.py:204:42: B023 Function definition does not bind loop variable 'discr'.
return actx.to_numpy(op.norm(discr, x, np.inf))
^
test/test_euler.py:170:42: B023 Function definition does not bind loop variable 'discr'.
return actx.to_numpy(op.norm(discr, x, np.inf))
^
test/test_euler.py:278:37: B023 Function definition does not bind loop variable 'vortex'.
return make_fluid_state(vortex(x_vec=nodes, **kwargs), gas_model)
^
test/test_euler.py:278:50: B023 Function definition does not bind loop variable 'nodes'. …
```
=> Ignore spurious `flake8-bugbear` `B023` error in tests

mirgecom/simutil.py
=> Suggest changes on get_sim_timestep docs/implementation.

mirgecom/boundary.py
Fixing some bugs and improving documentation for the boundary conditions regarding https://github.com/illinois-ceesd/mirgecom/pull/678
@MTCam , should we include here the changes in https://github.com/illinois-ceesd/mirgecom/pull/625 ?
=> Fixing Mengaldo BCs concerning grad(cv)

test/test_viscous.py
=> Add missing kinetic energy in cv.energy for power law transport test.

mirgecom/boundary.py, mirgecom/eos.py, mirgecom/initializers.py, mirgecom/io.py, mirgecom/operators.py, mirgecom/steppers.py, mirgecom/viscous.py, test/test_av.py, test/test_diffusion.py, test/test_euler.py, test/test_filter.py, test/test_init.py, test/test_wave.py
=> Fix up linting issues after flake8 update.

mirgecom/eos.py
=> Sharpen mixture `gamma` docstring

bin/mirgecompare.py, mirgecom/simutil.py
Default field-specific tolerances organized by a tolerance dictionary
Closes https://github.com/annabellej/mirgecompare/issues/20
=> field-specific tolerance added by dictionary

mirgecom/simutil.py
Rank number feature by XML parsing through pvtu files
=> Mirgecompare: check that rank numbers match

test/test_av.py
=> Also rename `disc` to `dcoll`

mirgecom/mpi.py
This makes debugging multi-rank GPU runs easier. 
---
=> Demote GPU oversubscription to a warning

mirgecom/simutil.py
=> get_reasonable_memory_pool: also show dev name in SVM case

mirgecom/simutil.py
=> get_reasonable_memory_pool: fix string

doc/faq/errors.rst
A bit bleak, but that's all we have at the moment.
---
=> doc: CUDA_ERROR_FILE_NOT_FOUND

examples/run_examples.sh
Adds:
- just a little more transition between examples for better eye-parsing of github CI output
- `date` for rough timing of examples and runner script
- report the command used for spawning the examples
- add some support for running the runner script on Lassen
=> Examples runner update

examples/wave.py
=> wave example: use get_reasonable_array_context_class

mirgecom/simutil.py
=> get_reasonable_memory_pool: also show device in 3rd case

examples/autoignition-mpi-lazy.py, examples/doublemach-mpi-lazy.py, examples/hotplate-mpi-lazy.py, examples/nsmix-mpi-lazy.py, examples/poiseuille-mpi-lazy.py, examples/run_examples.sh, examples/sod-mpi-lazy.py
Follow-on to #766, and eliminates #666.  This change set makes the examples run in lazy mode in CI.
=> Add lazy examples.

examples/nsmix-mpi.py, mirgecom/transport.py
=> Add Lewis to PowerLaw on PhysAV branch

requirements_dev.txt
[pyrasite](https://github.com/lmacken/pyrasite) can be used to inject python code into *running* python processes, useful e.g. for getting a stack trace at runtime without stopping the application:
```bash
$ pyrasite-shell <PID>
```
```python
import sys, traceback
for thread_id, frame in sys._current_frames().items():
print("Stack for thread {}".format(thread_id))
traceback.print_stack(frame)
print("")
```
This even works with MPI.
---
=> add pyrasite to dev packages

mirgecom/diffusion.py, mirgecom/navierstokes.py
Together with illinois-ceesd/drivers_y2-prediction#14 and a couple of changes in #767, partially addresses #783.
=> Add missing comm tag forwarding

.github/workflows/ci.yaml
Might help in debugging spurious failures like https://github.com/illinois-ceesd/mirgecom/actions/runs/3298510399/jobs/5440723404#step:5:7545
=> Porter CI: run with POCL_DEBUG

.ci-support/merge-install-production-branch.sh, .ci-support/production-drivers-install.sh, .ci-support/production-drivers-run.sh, .github/workflows/ci.yaml, examples/run_examples.sh, mirgecom/mechanisms/__init__.py
This change set:
- drops `nozzle` out of production testing
- adds prediction-driver smoke test
- run the production tests in distributed-lazy mode
- adds script support for running production tests on Lassen and Porter
=> Replace nozzle production test with prediction test.

examples/run_examples.sh, scripts/install-production-drivers.sh, scripts/merge-install-production-branch.sh, scripts/mirge-testing-env.sh, scripts/run-driver-smoke-tests.sh, scripts/run-integrated-tests.sh, scripts/run-production-tests.sh
Hopefully fix grudge CI testing of downstream projects without requiring them to change.
=> Use default value for all potentially unbound shell vars.

.rtd-env-py3.yml, conda-env.yml, mirgecom/fluid.py
=> Testing Python 3.11

.rtd-env-py3.yml, conda-env.yml, mirgecom/fluid.py
cc #786 
https://docs.python.org/3.11/whatsnew/3.11.html
Highlights:
- Substantial performance improvements
- Further debugging improvements (https://docs.python.org/3.11/whatsnew/3.11.html#whatsnew311-pep657)
Needs:
- ~~https://github.com/conda-forge/pyopencl-feedstock/pull/102~~
- ~~https://github.com/conda-forge/mypy-feedstock/pull/76~~
=> Python 3.11

.rtd-env-py3.yml
=> Fix readthedocs build

examples/autoignition-mpi.py, mirgecom/gas_model.py, mirgecom/limiter.py
=> Production refac lim

.github/workflows/ci.yaml
This reverts commit 3b3693ddee2609afa57ac8048ab4753b7a9340b2 / #803.
flake8-quotes v3.3.2 is compatible with flake8 v6.
=> Revert "Restrict flake8 version (#803)"

.github/workflows/ci.yaml
=> Fix homebrew CI failure

.github/workflows/ci.yaml, mirgecom/eos.py, mirgecom/gas_model.py, mirgecom/logging_quantities.py, mirgecom/mpi.py, mirgecom/profiling.py, mirgecom/simutil.py, mirgecom/transport.py, mirgecom/utils.py, setup.cfg
=> Fix mypy errors and add mypy to CI

mirgecom/logging_quantities.py, mirgecom/profiling.py, setup.cfg
=> logpyle-related mypy fixes

doc/running/large-systems.rst, mirgecom/mpi.py
=> warn when cache dirs are not rank-specific on a node

doc/conf.py, doc/running/profiling.rst
=> add memray documentation

examples/thermally-coupled-mpi.py, mirgecom/multiphysics/thermally_coupled_fluid_wall.py
Testing CI after merge with @majosm wall-coupling.
=> Wall coupling production

mirgecom/simutil.py, setup.cfg
=> get_reasonable_memory_pool: allow control over allocation

examples/heat-source-mpi.py, examples/wave-mpi.py, examples/wave.py
...otherwise, results tend to get lost 😬
=> make sure to close logmgr

examples/wave-mpi.py, examples/wave.py, mirgecom/logging_quantities.py
Not sure if it is better to make this a separate function or add it to `logmgr_add_device_memory_usage`.
=> add MemoryPool logging

mirgecom/io.py
=> Extend step field for viz file names

mirgecom/steppers.py
Needed for https://github.com/illinois-ceesd/drivers_y3-prediction/pull/6.
=> Make RHS compile optional in `advance_state`

mirgecom/logging_quantities.py
needs https://github.com/illinois-ceesd/logpyle/pull/81
=> add GCStats

scripts/production-testing-env.sh
Currently points at a driver branch with some slight changes for the new Y3 driver.  The Y3 driver PR  (https://github.com/illinois-ceesd/drivers_y3-prediction/pull/1) should be merged and this change set fixed to use driver@main before this merges to mirgecom@main.
=> Update production driver to Y3

mirgecom/navierstokes.py
Feature request from @tulioricci 
=> Add option to turn off inviscid terms in CNS operator.

doc/discretization.rst, examples/autoignition-mpi.py, examples/doublemach-mpi.py, examples/doublemach_physical_av-mpi.py, examples/nsmix-mpi.py, examples/poiseuille-local_dt-mpi.py, examples/poiseuille-multispecies-mpi.py, examples/vortex-mpi.py, mirgecom/boundary.py, mirgecom/gas_model.py, test/test_bc.py
Test these changes to production.
=> Production udmg

doc/discretization.rst, mirgecom/boundary.py, mirgecom/gas_model.py, test/test_bc.py
This PR:
1. Splits the individual aspects of each BC into separate `_*BoundaryComponent` classes (e.g. `_AdiabaticBoundaryComponent`, `_NoSlipBoundaryComponent`) so that the code can be more easily reused. The fluid boundary objects now use these internally to get the respective boundary subcomponent values when assembling boundary state, etc.
2. Replaces the Mengaldo inviscid/viscous flux methods with calls to standalone flux functions that have callback inputs for boundary values. After the above changes, these were pretty much all doing the same thing and didn't need to be defined separately for each BC. 
3. Adds a `replace_fluid_state` function to eliminate some of the boilerplate code for creating modified states in the BCs.
I also made an attempt here to be a bit more precise about …
=> Attempt to reduce code duplication in BCs

mirgecom/integrators/__init__.py, mirgecom/integrators/ssprk.py, test/test_time_integrators.py
=> Tweak SSPRK43 -> SSPRK34, tests

conda-env.yml
Shouldn't be necessary anymore since https://github.com/conda-forge/gmsh-feedstock/pull/72 has been merged.
=> Undo manual occt pinning

examples/autoignition-mpi.py, mirgecom/thermochemistry.py
Add extra function in Thermochemistry to evaluate chemical energy release.
This is a visualization-only function, so I wonder if this is the best place to add this. Open to suggestions.
**Questions for the review** @MTCam :
- There are no tests (I don't _think_ its a problem for this, but couldn't hurt to add one at least to demonstrate its use.)
=> Add extra function to evaluate heat release

mirgecom/logging_quantities.py
=> warn when memory usage is high on the GPU

requirements_dev.txt
=> add Python 3.11-compatible vmprof

doc/faq/errors.rst, doc/running/caching.rst, doc/running/large-systems.rst, doc/running/running.rst, mirgecom/logging_quantities.py
Not sure if there are other things cached apart from kernels.
=> doc: document kernel caching

conda-env.yml
=> explicitly install vtk

examples/combozzle-mpi.py, examples/heat-source-mpi.py
=> Logging fixes

mirgecom/diffusion.py, test/test_diffusion.py
Tweaks `diffusion_operator` so that in the case of `u` being an object array, `kappa` can either be a scalar (existing behavior) or an object array.
=> Allow `kappa` to be either a scalar or a vector in vectorized `diffusion_operator`

mirgecom/euler.py, mirgecom/navierstokes.py
=> Add warning when using unlimited mixture states.

doc/faq/install.rst
=> doc: fix PyOpenCL configure paths

.ci-support/install.sh
=> Work around brotli failure in CI

mirgecom/boundary.py, mirgecom/multiphysics/thermally_coupled_fluid_wall.py, mirgecom/utils.py, test/test_multiphysics.py
=> Test radiation feeder on production

mirgecom/mpi.py
Code based on https://github.com/inducer/islpy/issues/28#issuecomment-702408541
---
=> add a check for ISL version

mirgecom/artificial_viscosity.py
=> Add isothermal wall to AV boundaries needed by flame1d

doc/fluid.rst
=> Remove stale and untruthful note

mirgecom/eos.py, mirgecom/gas_model.py
=> Update deprecated zeros_like usage

examples/lump-mpi.py, examples/nsmix-mpi.py, examples/poiseuille-mpi.py, examples/scalar-advdiff-mpi.py, mirgecom/multiphysics/thermally_coupled_fluid_wall.py
Testing with esdg changes factored out.
=> Add ESDG option to production

doc/conf.py, doc/support/tools.rst, examples/autoignition-mpi.py, examples/combozzle-mpi.py, examples/doublemach-mpi.py, examples/doublemach_physical_av-mpi.py, examples/heat-source-mpi.py, examples/hotplate-mpi.py, examples/lump-mpi.py, examples/mixture-mpi.py, examples/multiple-volumes-mpi.py, examples/nsmix-mpi.py, examples/poiseuille-local_dt-mpi.py, examples/poiseuille-mpi.py, examples/pulse-mpi.py, examples/scalar-advdiff-mpi.py, examples/scalar-lump-mpi.py, examples/sod-mpi.py, examples/thermally-coupled-mpi.py, examples/vortex-mpi.py, examples/wave-mpi.py, examples/wave.py, mirgecom/array_context.py, mirgecom/simutil.py, scripts/production-testing-env.sh
=> factor out actx init

.rtd-env-py3.yml
Fixes the RTD build: https://readthedocs.org/projects/mirgecom/builds/21282958/
=> add scipy dependency for RTD build

examples/ablation-workshop-mpi.py
=> Use binary recursive sum to reduce DAG depth resulting from spline evaluation in ablation workshop example

examples/run_examples.sh
Fixes #957 up so that the examples actually run from the user's location.  
=> Change request to runex fix 

examples/run_examples.sh, examples/thermally-coupled.py
This is how the grouping looks like:
=> run_examples.sh: fix running from different dir, add GitHub actions log grouping

mirgecom/boundary.py
Moves this production change to main.   Both BR1 and Mengaldo indicate we should prescribe this flux at the boundary for grad calcs, instead of using central.
=> Use built-in LDG bnd flux

mirgecom/boundary.py, mirgecom/simutil.py
=> Use PKL5 Comm wrapper and time mesh gen/read/dist

mirgecom/logging_quantities.py
=> Logging: add PythonInitTime

mirgecom/simutil.py
=> distribute_mesh: add more logpyle

examples/ablation-workshop.py, mirgecom/utils.py
=> add force_compile function

examples/ablation-workshop.py, mirgecom/mpi.py, scripts/delta-parallel-spawner.sh, scripts/delta.sbatch.sh, scripts/lassen-parallel-spawner.sh, scripts/lassen.bsub.sh, scripts/mirge-testing-env.sh
=> add scripts for delta

.readthedocs.yml, .rtd-env-py3.yml
Fixes the RTD build, addressing the recent deprecations.
=> Fix RTD build

mirgecom/logging_quantities.py
=> logging: save logpyle DB on SIGTERM

examples/ablation-workshop.py, mirgecom/eos.py, mirgecom/gas_model.py, mirgecom/transport.py
Extends dv and gas model to handle an additional term that represents extra diffusivity at species interfaces.
-  See review comment.
=> Add av diff

.github/workflows/ci.yaml
=> Clean up temp files on porter before CI runs

test/test_viscous.py
=> Remove blank line in test_viscous (fix conflict)

examples/sod.py, examples/taylor-green.py, examples/vortex.py
=> Fix flake8 in CI

mirgecom/navierstokes.py
=> Add missing args to grads inside ns_operator

conda-env.yml
Do not update cantera to 3.0 yet.
See https://github.com/illinois-ceesd/mirgecom/issues/988 and https://github.com/pyrometheus/pyrometheus/pull/75
=> Keep cantera in version 2.6.0 for now

test/test_eos.py
=> Keep commented line in test_eos (fix conflict) 

.github/workflows/ci.yaml
=> disable ocl-icd-system for porter

.github/workflows/ci.yaml
Avoids warnings of the type:
```
[pydocstyle](https://github.com/illinois-ceesd/mirgecom/actions/runs/7905730621/job/21579009137)
Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: actions/checkout@v3, actions/setup-python@v4. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.
```
=> Bump CI component versions

.github/workflows/ci.yaml
Followup of #994 (via https://github.com/conda-forge/openvino-feedstock/pull/73)
=> remove porter ocl-icd-system workaround

mirgecom/simutil.py
=> Fix local-dt for multiple domains

mirgecom/gas_model.py
This change makes the calls compliant, the "tag" argument has been deprecated for some time.
=> Fix up the interior_trace_pairs calls for smoothness fields.

mirgecom/transport.py
=> Add pressure-dependence to species diffusion in PowerLaw

mirgecom/transport.py
Reverts #1014 (by request). cc @tulioricci 
=> Revert #1014

doc/running/caching.rst, mirgecom/mpi.py
See https://github.com/platformdirs/platformdirs/issues/4 and https://github.com/platformdirs/platformdirs/blob/7039c66b02f50fca54b965dcb2bd9de865d06cb8/src/platformdirs/macos.py#L56-L58 for context.
cc @MTCam , @inducer 
=> doc: fix MacOS kernel disk caching wrt XDG_CACHE_HOME

.github/workflows/ci.yaml
=> Work around CI failure

examples/autoignition.py, examples/scalar-advdiff.py, mirgecom/gas_model.py, test/test_limiter.py
Update limiting API to be compatible with current versions and implementations of limiters from the prediction simulation.
cc: @tulioricci @anderson2981 
=> Update limiter API, examples.

mirgecom/mpi.py
I that case, pocl will just use XDG_CACHE_HOME
=> don't bother checking POCL_CACHE_DIR if XDG_CACHE_HOME is set

examples/blasius.py, examples/thermally-coupled.py
Merge this to fix a pylint error that occurs after upstream pkg updates.
=> disable pylint unpack err

scripts/delta.sbatch.sh, scripts/lassen.bsub.sh, scripts/quartz.sbatch.sh, scripts/tioga.flux.sh
=> use mirge-cache-root in example batch scripts

examples/ablation-workshop.py, mirgecom/eos.py, mirgecom/thermochemistry.py
Refactor `get_temperature` to compute from energy or enthalpy.  This version matches up with mixture fraction EOS.
=> refactor mixture get_temperature 

examples/ablation-workshop.py, examples/advdiff-tpe.py, examples/blasius.py, examples/combozzle.py, examples/doublemach_physical_av.py, examples/orthotropic-diffusion.py, examples/scalar-advdiff.py
=> Relint: eliminate pylint errors.

mirgecom/array_context.py
- reflect that `LOOPY_NO_CACHE`/`PYOPENCL_NO_CACHE` use `strtobool` now
- fix `actx_class_is_pyopencl`
- `POCL_CACHE_DIR` overrides `XDG_CACHE_HOME` for pocl
=> cache logging fixes

mirgecom/eos.py, test/test_eos.py
=> Add function to compute mole fractions from mass and vice-versa

examples/gas-in-box.py, mirgecom/discretization.py, test/test_operators.py
- Unifies discretization collection creation for TPEs/Simplices (thanks to support in _grudge_)
- Updates gas-in-box example:
- Use updated dcoll creation
- CL Option Euler timestepping
- CL Option nsteps
- Adds some more grad operator tests for TPEs
- Updates grad test to include a "wonky" mesh test, and rotated mesh tests
=> Evolve TPE integration

mirgecom/thermochemistry.py
Leftover change that I forgot to add to #1051.
=> Remove last use of `PyroWrapper.wts`

.ci-support/install.sh
cc https://github.com/illinois-ceesd/emirge/pull/174
=> use miniforge in CI

test/test_av.py, test/test_chemistry.py, test/test_eos.py, test/test_init.py, test/test_transport.py
=> use actx_factory in tests

examples/run_examples.sh, mirgecom/array_context.py
The underlying PRs have been merged.
=> make NumpyArrayContext non-optional

conda-env.yml
=> Revert cantera change

conda-env.yml
=> add nvtop to conda dependencies

doc/conf.py, test/test_symbolic.py
=> Fix up some lingering doc/pymbolic issues 

examples/ablation-workshop.py, examples/wave.py, mirgecom/eos.py, mirgecom/inviscid.py, mirgecom/materials/carbon_fiber.py, mirgecom/materials/prescribed_porous_material.py, mirgecom/materials/tacot.py, mirgecom/simutil.py, mirgecom/transport.py, mirgecom/wall_model.py
=> Remove unused type ignores

.ci-support/install.sh, .github/workflows/ci.yaml, examples/blasius.py
=> blasius workaround & CI cleanup

mirgecom/simutil.py
=> add queue_finish helper function
