illinois-ceesd/mirgecom

- mirgecom/symbolic.py
- test/test_wave.py
Combines existing wave tests into one test parametrized on the problem being solved, and separates symbolic bits into a module for other tests to use.
Closes #17
> Clean up wave tests

- .github/workflows/tests.yaml
Use 'python setup.py install' rather than 'pip install .' to avoid spurious installation of old loopy.
x-ref: https://gitlab.tiker.net/inducer/ci-support/-/commit/fc8c4b779b34404832b0426aa8f49c445d3e3a2a
> Work around pip breakage

- requirements.txt
x-ref: https://github.com/inducer/meshpy/issues/50
I don't think we need it for anything. (We use gmsh for mesh generation after all.)
cc @majosm
> Drop meshpy from requirements.txt

- examples/wave-eager-mpi.py
- examples/wave-eager.py
Reduces memory allocations from 300,000 to 160.
15% speedup.
Addresses #66.
> use pooled allocator

- doc/index.rst
Makes it easier to refer people to specific parts of the documentation.
> doc: number sections

- examples/lump-mpi.py
- examples/sod-mpi.py
- examples/vortex-mpi.py
- mirgecom/simutil.py
* Adds parallel grid generator common to all examples
* Generalizes checkpoint to be used even for sims without exact soln (needed for Y0/Y1 )
* Adds a placeholder for profiling util (also used in Y0/Y1 example)
Note: Y0/Y1 Euler example will follow in a separate PR
> Refactor some common utilities into simutils

- mirgecom/profiling.py
Fixes
`
/usr/WS1/diener3/Work/emirge/mirgecom/mirgecom/profiling.py:156: FutureWarning: Format strings passed to MaskedConstant are ignored, but in future may error or produce different behavior
fprint_min, f"{fprint_mean:{g}}", fprint_max,
`
> profile: fix footprint mean warning

- .rtd-env-py3.yml
- .test-conda-env-py3.yml
Python 3.9 seems to have broken many of our installation/readthedocs/CI workflows. As an example, the documentation CI shows:
```
The following packages will be SUPERSEDED by a higher-priority channel:
pytest             conda-forge/linux-64::pytest-6.1.1-py~ --> conda-forge/noarch::pytest-3.2.2-py_0
```
See also https://github.com/majosm/squirm/commit/ecfb9b48f698dd2ce0fd21e46c3e52ffd9f0b36b
> work around Python 3.9/conda clusterfsck

- mirgecom/prometheus.py
- test/test_eos.py
This changes the prometheus uiuc mechanism port to use a passed-in numpy context.   Just testing and discussing here.  Once we have this worked out, we'll update the pyrometheus code generator to reflect our current expression for the themochemistry object.
cc: @inducer , @ecisneros8
> Update prometheus object to take numpy-like namespace for numpy-like ops

- mirgecom/mpi.py
Fixes https://github.com/illinois-ceesd/emirge/issues/73
Fixes pocl-related crashes of the type:
```
Not enough memory to run on this device.
```
at startup.
These happen only when running with mpi4py, e.g. 
```
$ python wave-eager.py
``` 
works fine with the "wrong" libhwloc version, but
```
$ python -m mpi4py wave-eager-mpi.py
```
does not. 
The reason for the error is that since we are building mpi4py from source against the system MPI and hwloc, but pocl against conda's hwloc, the two hwloc versions might be different (v1 vs. v2). Since libhwloc v1/v2 internally use the same version number, only one version can be loaded at a time, which means that the first package that loads hwloc determines the hwloc version for everyone else. 
This seems to be especially problematic when pocl is …
> Avoid hwloc version conflicts by forcing pocl to load before mpi4py

- examples/vortex-mpi.py
Background: Running this with `dim=3` just hangs.
> vortex-mpi: Don't run in 3D, fix warning

- mirgecom/profiling.py
Fixes #177.
Approx. ~10%~ -2% overhead vs. profiling with `master` branch.
> profiling: don't carry kwargs around

- examples/lassen.bsub.sh
- examples/quartz.sbatch.sh
Lassen+Quartz:
- Print nnodes/nproc to aid in reproducing runs
- add -O option to Python command line (Fixes #195)
Lassen:
- Use jsrun instead of lrun
- Use GPU by default
- Print task allocation to aid in checking that it is doing what we expect
> batch script fixes

- mirgecom/euler.py
This is an attempt to add some documentation for the expected shape for the flux data.  As fluxes are typically internal-only data, folks adding new capabilities (e.g. new numerical flux routines) will need to know the expected shape of the arrays.
It is easy to run afoul of the expectation.  Here's an example of that from @w-hagen:
```
vol_flux = inviscid_flux(discr, eos, q)
print(vol_flux.shape)
print(vol_flux[0].shape)
```
> returns (4,2), (2,) not (4,), (2,) like my arrays do
> Doc for flux shapes

- mirgecom/euler.py
This just removes the documentation of sources from Euler, per the plan to leave source terms up to the user.
> Remove source term documentation in Euler

- pytest.ini
- test/test_diffusion.py
This is to help https://github.com/inducer/meshmode/pull/114 avoid having to (somewhat pointlessly) run Octave tests.
> Mark tests needing Octave

- conda-env.yml
background: the gmsh package doesn't exist for power9, so installs on Lassen fail at the moment. If we need the package for CI in the future, it should probably be installed in the CI scripts.
> remove gmsh from conda

- doc/misc.rst
- mirgecom/butcher_tableau.py
- mirgecom/integrators.py
- test/test_time_integrators.py
Howdy!
I've just installed mirgecom and noticed ya'll have the LSRK 5-stage, 4th order method by Kennedy and Carpenter, so I thought I'd add another LSRK method. The method I have added is a 14-stage, 4th order method summarized in the following paper (Table 3): https://www.sciencedirect.com/science/article/pii/S0021999111005213?via%3Dihub
It possesses an optimized stability region for advection-dominated flows, and is capable of taking much larger time-steps than the RK4 or LSRK4 methods. I've seen nice results in terms of time-to-solution using this 14-stage method in other DG codes I have experimented with, and I thought I would add this to mirgecom too. This hopefully can help speed up the time-to-solution for people running tests and simulations.
As a quick example, I ran the …
> Add the 14-stage, 4th order LSRK method of Niegemann, Diehl, and Busch (2012)

- requirements.txt
Add _logpyle_ to development packages so that we can pick up current performance logging features when we perform automated build-and-test (e.g. enabling https://github.com/illinois-ceesd/timing/issues/1 in https://github.com/illinois-ceesd/timing/pull/2)
> Add logpyle to development packages.

- mirgecom/integrators/__init__.py
- mirgecom/integrators/lsrk.py
Function rename for LSRK4 caused outstanding drivers using it to fail.  This patch brings back a backwards-compatible interface with a warning. cc @thomasgibson @anderson2981
> Add backwards-compatible API for LSRK4.

- mirgecom/diffusion.py
- test/test_diffusion.py
Redefines `q` to be `grad(u)` instead of `sqrt(alpha)*grad(u)`. I opted to just call it `grad_u` instead of `q`. Seems a little more readable that way.
Depends on #296 and inducer/grudge#60. Closes #291.
> Add support for discontinuous alpha in diffusion_operator

- setup.cfg
flake8 finding these files are quite annoying with pre-commit hooks enabled.
> Flake8 ignore emacs temporary backup and hidden files.

- examples/heat-source-mpi.py
- mirgecom/diffusion.py
- test/test_diffusion.py
Importing objects like `QTAG_NONE`, `DOFDesc`, `as_dofdesc` and others should now be imported directly from `grudge.dof_desc` (see https://github.com/inducer/grudge/pull/75)
> Remove importing `grudge.dof_desc` objects from `grudge.symbolic.primitives`

- doc/conf.py
- requirements.txt
- setup.py
This isn't technically needed yet (`arraycontext` is nothing but an empty shell for now), but it'll help me with some [upstream PR headaches](https://github.com/inducer/meshmode/pull/181).
> Add forward-looking dependency on arraycontext

- examples/doublemach-mpi.py
- mirgecom/euler.py
This fixes bugs in passing the time dependent boundary conditions to the euler_operator, and similar issues when calling the av_operator in the doublemach case
> Fix passing of time variable to boundary

- conda-env.yml
Fixes the logpyle issues seen on Lassen etc. 🤷 
cantera depends on h5py, which depends on hdf5 (and therefore MPI). Force the non-MPI version of h5py to be installed.
> cantera: make sure not to pull in MPI

- mirgecom/profiling.py
- requirements.txt
Draft because:
Context: https://github.com/inducer/loopy/pull/222/ just merged. It broke some internal interfaces that mirgecom's profiling was using. This PR fixes that. If you see examples CI failures, that's what's happening.
> Fix profiling array context for kernel callables

- mirgecom/profiling.py
This is in preparation for https://github.com/inducer/arraycontext/pull/22. Without this, the examples CI at https://github.com/inducer/meshmode/pull/218 fails.
> Add PyOpenCLProfilingArrayContext.clone

- doc/support/arrays.rst
- setup.cfg
cc @matthiasdiener @majosm @thomasgibson for disabling flake8's N818: "All exception classes must end in `Error`". I'm not a fan, but I figured I'd put it up for debate.
> Fix doctest update

- .github/workflows/ci.yaml
- mirgecom/profiling.py
This fixes a large part of the CI slowness w/ profiling.
> Replicate call_loopy changes from pyopencl actx base class

- .ci-support/production-driver-setup.sh
- .ci-support/production-setup.sh
- .github/workflows/ci.yaml
This adds a production case checker to the CI, to test changes to main against our production problem.
- Uses emirge to install the default `y1-production`
- Uses .ci-support/production-setup.sh to apply any changes to `y1-production` that could be required to support the current change-set
- Merges the current change-set to `y1-production`
- Checks out the default production driver (nozzle)
- Uses .ci-support/production-driver-setup.sh to apply any changes to the production driver required to support the current change-set
- Runs @anderson2981's production driver test (smoke_test)
Let's say you have a change to make to main, by default this CI will check that if `y1-production` merges the "new main" (i.e. main with your changes applied) will result in a running production problem.  If …
> Add Y1 production test to CI

- .ci-support/.gitattributes
- .github/workflows/ci.yaml
Keeps merges from changing the production tests. Unrelated: removes CI environment inspection.
> Add gitattributes preventing merge mods to production prep scripts

- mirgecom/logging_quantities.py
Should fix https://github.com/illinois-ceesd/logpyle/issues/70
When running `python -m mpi4py examples/vortex-mpi.py`:
before:
`step.max=0 | t_step.max=0.357478s | t_log.max=9.13143e-05s | min_temperature=0 | L2_norm_momentum1=0 | memory_usage_python.max=106.734MByte |`
after:
`step.max=0 | t_step.max=0.366507s | t_log.max=5.31673e-05s | min_temperature=0.00231604 | L2_norm_momentum1=9.96694 | memory_usage_python.max=130.578MByte |`
> Logging: Convert to post LogQuantity

- examples/autoignition-mpi.py
- examples/doublemach-mpi.py
- examples/heat-source-mpi.py
- examples/lump-mpi.py
- examples/mixture-mpi.py
- examples/nsmix-mpi.py
- examples/poiseuille-mpi.py
- examples/pulse-mpi.py
- examples/scalar-lump-mpi.py
- examples/sod-mpi.py
- examples/vortex-mpi.py
- mirgecom/boundary.py
This unifies the argparse and main signature across fluidy examples, and does the easy part of enabling lazy execution.
> Laxify the examples in production

- .github/workflows/ci.yaml
Use pulse as a test problem instead of wave-eager-mpi, which is sort of going away anyway.
> Test pulse, not wave

- .ci-support/production-install.sh
- .ci-support/production-testing-env.sh
This change set uses emirge fork support to deeply simplify the production testing - which is now *much* closer to @matthiasdiener's preference:
1. install user's development (automatic, specify fork if needed)
2. merge the production environment (fork and branch customizable)
3. install production requirements.txt
4. run the user's production driver (fork and branch customizable)
If running on main, all user customizations are ignored. The defaults are
those which main uses. (illinois-ceesd, y1-production, nozzle)
> Update to emirge fork support

- mirgecom/steppers.py
This was some oversight in our changes to stepper to support lazy - leap needs to know when dt changes.
> Correct the leap stepper for dt modification

- examples/mixture-mpi.py
This case was taking up a giant portion of the examples section of CI.  This just makes it 2D, so that it can do more steps much faster.
> Dumb down the mixture case to make it run much faster.

- test/test_lazy.py
Only diffusion/Euler for now. Production version with NS/AV [here](https://github.com/majosm/mirgecom/blob/lazy-operator-tests-ns-av/test/test_lazy.py).
> Add tests for lazily-compiled operators

- mirgecom/profiling.py
This restores profiling of the elwise kernels.
Grudge e.g. creates temporary (?) actx copies when building face connections that will point the exec hook to an actx that isn't used throughout the actual execution.
> profiling: fix elwise kernel exec hook

- test/test_euler.py
- test/test_inviscid.py
This simply splits the tests into two different testing files to give symmetry to the inviscid/Euler, viscous/NavierStokes testing infrastructure.
> Split the tests into inviscid and euler

- mirgecom/transport.py
This change set enables the power law transport model by using the built-in (**) operator instead of the spurious actx.np.power function.   Some superfluous asserts are also removed.
> Fix and enable power law transport model

- mirgecom/symbolic.py
- test/test_diffusion.py
Simplifies the implementation of `sym.div` and makes `sym.grad` return an object array. (Is there any reason it might not be OK to return an object array here, @inducer? I couldn't figure out why I made it return a list originally.)
> Tweak symbolic `div` and `grad`

- test/test_lazy.py
This is for the benefit of https://github.com/inducer/grudge/pull/161, which starts using P^0 (that is, constant) geometry terms for affinely mapped simplices whenever possible, for a major cost reduction and additional transform opportunities. (Doing so requires broadcasting semantics, which are only properly implemented for lazy eval, so this only benefits lazy for the moment.)
I'm not super worried about these tolerance bumps; if anything, I'd expect the P^0 geometry to be *more* accurate (but quite possibly a bit different from our prior all-curvi approach).
> Bump tolerances in test_lazy for P^0 geometry

- examples/lump-mpi.py
- examples/mixture-mpi.py
- examples/pulse-mpi.py
- examples/scalar-lump-mpi.py
- examples/sod-mpi.py
- examples/vortex-mpi.py
Fixes the restart reading to use the same name for the partition count when reading as when writing (`num_parts`).
> Fix restart reading of `num_parts` in examples

- doc/development/pullrequests.rst
I think it makes sphinx view this as a quote, leading to an inexplicable extra vertical ine:
> Remove extraneous indentation in PR dev docs

- .ci-support/production-testing-env.sh
- examples/autoignition-mpi.py
- examples/doublemach-mpi.py
- examples/poiseuille-mpi.py
- examples/pulse-mpi.py
- mirgecom/artificial_viscosity.py
- mirgecom/boundary.py
- mirgecom/euler.py
- mirgecom/gas_model.py
- mirgecom/inviscid.py
- mirgecom/navierstokes.py
- mirgecom/operators.py
- mirgecom/utils.py
- mirgecom/viscous.py
- test/test_av.py
- test/test_bc.py
- test/test_lazy.py
- test/test_operators.py
- test/test_viscous.py
This PR add overintegration support for the main production branches (based on the new state-handling). In the process of adding overintegration to the AV and NS operators, I also did some rewriting to (hopefully) make it a bit easier to follow.
Update: since we plan to eventually add a NS-style artificial viscosity operator, I've taken this opportunity to rename `av_operator` to `av_laplacian_operator`. There is a backwards compact interface as well: https://github.com/illinois-ceesd/mirgecom/pull/570/commits/af8cccf7b088861649e02ded5623aded32dcb2aa
> Operator overhaul and overintegration support for all fluid-based operators

- mirgecom/boundary.py
- mirgecom/euler.py
This change set just renames `inviscid_boundary_flux` --> `inviscid_divergence_flux` per discussions in downstream viscous/NS PRs.  
> Inviscid boundary interface

- .ci-support/production-testing-env.sh
- mirgecom/euler.py
- mirgecom/filter.py
- mirgecom/simutil.py
- test/test_euler.py
- test/test_filter.py
- test/test_fluid.py
- test/test_lazy.py
- test/test_operators.py
- test/test_restart.py
- test/test_simutil.py
- test/test_viscous.py
This PR does exactly what the title suggests. It removes all `.join()` calls!
> Purge `.join()` from mirgecom

- .ci-support/install.sh
- https://github.com/mpi4py/mpi4py/issues/157
- https://github.com/illinois-ceesd/emirge/pull/143
- https://github.com/illinois-ceesd/mirgecom/pull/584
> mpi4py workaround

- doc/support/math.rst
- doc/support/support.rst
- mirgecom/math.py
- mirgecom/symbolic.py
- test/test_diffusion.py
Mostly minor changes here; the only real noteworthy change is the addition of ~~the `MathMapper` class, which is intended to be a numpy-like object~~ the math module and its `__getattr__` function that dispatches math function calls to either `np`, `np.actx`, or `pymbl.var(...)` depending on the types of the arguments.
I'm not sure if having the math mapper be a module instance is the best way to implement this, so I'm open to changing it if there's another way that's cleaner. I mainly just wanted to be able to `import mirgecom.math as mm` and then `mm.sin(...)` instead of having to `from mirgecom.math import sin`, etc. for each function used. Maybe this isn't such a big deal? I dunno. 🤷‍♂️ 
> Generalize symbolic helper code so it can be used more easily with other tests

- mirgecom/simutil.py
This maintains the same 'truthy' API as before, ie, returns `False` for a passing check, `True` for a failing check.
Drivers therefore don't necessarily have to be updated for this.
Driver code can use the values like this:
```python
failing_pres = global_reduce(check_range_local(discr, "vol", dv.pressure,
health_pres_min, health_pres_max),
op="lor")
if failing_pres:
logger.info(f"Pressure range violation ({health_pres_min=}, {health_pres_max=}, {failing_pres=})")
```
This helps with e.g. debugging https://github.com/illinois-ceesd/drivers_y2-isolator/issues/18
---
> check_range_local: report failing values

- .pylintrc.yml
- mirgecom/mechanisms/sanDiego.py
- mirgecom/mechanisms/uiuc.py
- mirgecom/thermochemistry.py
- setup.cfg
This change set adds the capability to use pre-generated thermochemical mechanisms.   
- Allows mechanisms from development version of Cantera required for adding mixture transport model
- Allows drivers to evict Cantera from runtime requirements (key in improving / enabling production driver compiles and reasonable runtimes)
- Imports actual code for mechanisms - allowing easy inspection by users
> Pre-generated thermochem

- examples/combozzle-mpi.py
- mirgecom/simutil.py
- mirgecom/steppers.py
Just testing using grudge compiled time integrator.  Not intended for merge (yet).  
> Add option to use grudge-based pre-compiled timestep.

- test/test_flux.py
- test/test_inviscid.py
https://github.com/inducer/grudge/pull/259 deleted the symbolic execution path in grudge. Since we got rid of mirgecom downstream CI in grudge (https://github.com/inducer/grudge/pull/221/files#r819008736), I had no idea about these now-stale references to the symbolic stuff in mirgecom.
This PR mops those up.
> Fix `TracePair` imports now that `grudge.symbolic` is gone

- examples/autoignition-mpi.py
- examples/heat-source-mpi.py
- examples/hotplate-mpi.py
- examples/lump-mpi.py
- examples/mixture-mpi.py
- examples/nsmix-mpi.py
- examples/poiseuille-mpi.py
- examples/pulse-mpi.py
- examples/scalar-lump-mpi.py
- examples/sod-mpi.py
- examples/vortex-mpi.py
- examples/wave-mpi.py
- examples/wave.py
- mirgecom/discretization.py
- mirgecom/simutil.py
This is a follow-on to #687 and #688.  It moves the examples from `EagerDGDiscretization` --> `DiscretizationCollection`.
Plus a couple of out-of-band changes:
- `discretization.py`: Update discr coll util to use `default_node_factory` util from `meshmode` 
- `simutil.py`: Resolve deprecated `asscalar@numpy`, fixes #691 
**Questions for the review** @lukeolson:
> Convert examples to use op namespace

- doc/index.rst
- mirgecom/boundary.py
- mirgecom/diffusion.py
- mirgecom/discretization.py
- mirgecom/gas_model.py
- mirgecom/inviscid.py
- mirgecom/operators.py
- mirgecom/viscous.py
- mirgecom/wave.py
- test/test_av.py
- test/test_viscous.py
- Banish Eager 
- Switch all discretization to `DiscretizationCollection` (for real)
- Clean up lingering issues exposed by switch
- switches to `interior_trace_pairs` to address deprecation (@lukeolson)
**Questions for the review** @lukeolson:
- ~~[ ] Is every top-level method and class documented? Are things that should be documented actually so?~~
> Switch to DiscretizationCollection@grudge

- examples/autoignition-mpi.py
- examples/doublemach-mpi.py
- examples/hotplate-mpi.py
- examples/lump-mpi.py
- examples/mixture-mpi.py
- examples/nsmix-mpi.py
- examples/poiseuille-mpi.py
- examples/scalar-lump-mpi.py
- examples/sod-mpi.py
- examples/vortex-mpi.py
- examples/wave-mpi.py
- examples/wave.py
The purpose of this change set is to clean up lingering deprecation warnings in the examples and further reduce the size of `production` diff against main.  In some cases (e.g. those with mixtures/chemistry), it is best to just use `production`'s version of the example as some changes are more difficult/tedious to unwind.
Common to all examples:
- Banished allsync
- Use `force_evaluation` when necessary
- Cleaned up thermochemical mechanism creation
- Updated deprecated logpyle API
Autoignition:
- Extended to provide lazy/chemistry testing with CNS/viscous terms
@lukeolson
> Clean up deprecations in examples

- test/test_eos.py
- test/test_viscous.py
Fixes the NaNs indicated by @majosm and appearing in this [CI run](https://github.com/illinois-ceesd/mirgecom/runs/7344124579) when order 2 norms are used for errors.
The ones appearing like the link below occur because the expected/cantera species concentrations can be 0, so relative errors NaN.  Switched this test to the more severe absolute difference comparison.
https://github.com/illinois-ceesd/mirgecom/runs/7344124579?check_suite_focus=true#step:4:57
The ones appearing at the next link occur because the kinetic energy was not added to the total energy in the power-law transport test.  This made the thermal state unphysical, and the power law test rightly failed.  Fixed by adding the kinetic energy.
https://github.com/illinois-ceesd/mirgecom/runs/7344124579?check_suite_focus=true#step …
> Avoid uncaught NaNs in some tests

- examples/autoignition-mpi.py
- examples/doublemach-mpi.py
- examples/heat-source-mpi.py
- examples/hotplate-mpi.py
- examples/lump-mpi.py
- examples/mixture-mpi.py
- examples/nsmix-mpi.py
- examples/poiseuille-mpi.py
- examples/pulse-mpi.py
- examples/scalar-lump-mpi.py
- examples/sod-mpi.py
- examples/vortex-mpi.py
- examples/wave-mpi.py
- examples/wave.py
- mirgecom/simutil.py
- requirements.txt
related PRs:
- https://github.com/pocl/pocl/pull/1067
- https://github.com/pocl/pocl/pull/1069
- https://github.com/inducer/pyopencl/pull/452
- https://github.com/inducer/loopy/pull/642
pocl conda files:
- x86_64: [pocl_svm_x86_64.tar.gz](https://github.com/illinois-ceesd/mirgecom/files/9313068/pocl_svm_x86_64.tar.gz)
> Use SVM memory pool

- mirgecom/artificial_viscosity.py
- mirgecom/diffusion.py
- mirgecom/euler.py
- mirgecom/gas_model.py
- mirgecom/navierstokes.py
- mirgecom/wave.py
...for disambiguating multiple operator calls within a single compiled function.
> Add optional user-specified `comm_tag` to operators

- mirgecom/diffusion.py
Split out from #726. Pulls the quadrature projection stuff up out of the flux and boundary functions.
---------------------
MTCam Review:
> Refactor diffusion to look more like Euler/NS

- requirements.txt
This change set will point `mirgecom@main` at the fusion array context, and upstream packages required for our prediction runs.  It renders our GPU testing more effective in that it speeds it up by more than an order of magnitude, and allows us to test lazy multi-species runs from main (which does not work with the default array context).
**Questions for the review** @lukeolson:
> Use fusion actx env.

- mirgecom/thermochemistry.py
- test/test_eos.py
Squash concentrations below `zero_level` to zero, preventing spurious reaction rates for insignificant concentrations of reactants.
> Add zero level option to thermochem interface.

- .github/workflows/ci.yaml
Due to https://github.com/zheller/flake8-quotes/issues/110
> Restrict flake8 version

- doc/misc.rst
- examples/autoignition-mpi.py
- examples/nsmix-mpi.py
- examples/pulse-mpi.py
- mirgecom/boundary.py
- mirgecom/initializers.py
- test/test_bc.py
Add no-shear stress condition for Symmetry/slip wall
Add RiemannInflow,
Add linearized Euler Eqs. for outflow
Rename OutflowBoundary to PressureOutflowBoundary
> Update Mengaldo BCs

- mirgecom/boundary.py
Updates the adiabatic slip boundary conditions to be in line with Mengaldo bcs. Replaces the existing bc implementation for AdiabaticSlip and removes the deprecation warning.
The major fix, vs the old implementation, is to modify the velocity gradients on the boundary to eliminate the shear stresses/fluxes.
One change is the computation of the viscous fluxes using the (numerical) viscous flux function instead of computing it directly. This is counter to what is outlined in Mengaldo, but allows more flexibility in the future if the user changes numerical flux functions for viscous terms.
> Fix AdiabaticSlip

- .github/workflows/ci.yaml
Fixes warnings of the type
- The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
- Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: actions/checkout@v2
> Update CI action components

- setup.py
With this PR, other packages using mirgecom can use mypy to check for type conformance with the mirgecom API.
See https://peps.python.org/pep-0561/ for context.
> add py.typed marker to "export" type info

- examples/wave-mpi.py
- examples/wave.py
also brings wave.py arguments in line with the other examples.
> wave-mpi: add --log, --profiling arguments

- mirgecom/integrators/__init__.py
- mirgecom/integrators/ssprk.py
- test/test_time_integrators.py
Add the 4-stages, 3rd order strong-stability preserving Runge-Kutta. Originally implemented in https://github.com/illinois-ceesd/mirgecom/pull/591
Closes https://github.com/illinois-ceesd/mirgecom/pull/591 and https://github.com/illinois-ceesd/mirgecom/pull/601
> Add SSPRK43 implemented by THG

- mirgecom/transport.py
> Modify MxTransp to handle single species case

- .github/workflows/ci.yaml
- mirgecom/io.py
- mirgecom/simutil.py
- requirements.txt
Some utilities used in prediction (and adjacent) simulations:
- read_and_distribute_yaml: Utility used by prediction drivers to read yaml config data
- boundary_report: utility to give a report on the numbers of mesh points on all surfaces and boundaries, used in performance analysis and modeling
-  geometric_mesh_partitioner: Used to give a 1D domain decomp for prediction meshes (dag splat mitigation)
- get_number_of_tetrahedron_nodes: Utility used for node counting in memory analysis and filter testing
- configurate: updated to be smarter about how it assigns default values/types
> Update some peripheral  utils for prediction

- mirgecom/multiphysics/thermally_coupled_fluid_wall.py
Currently, multiphysics runs with mixtures are sending unlimited fluid states to the fluid operators.   This change set fixes that issue.
> Add limiter_func to interface and pass to make_operator_fluid_states

- mirgecom/simutil.py
After revisiting https://github.com/inducer/meshmode/pull/342 and looking at how `mpi_distribute` is used inside `distribute_mesh`, I'm not sure it's actually needed anymore. `comm.scatter` may be good enough.
> Remove calls to `mpi_distribute`

- mirgecom/multiphysics/thermally_coupled_fluid_wall.py
~~Fixes~~ Mitigates a bug in the multiphysics interface that prevents callers from setting `inviscid_numerical_flux_func`.  
Defaulting this causes a pretty harmful thing.   If nothing is passed as `inviscid_numerical_flux_func` to `ns_operator`, then it defaults to `inviscid_facial_flux_rusanov`.    But if nothing is passed  as `inviscid_numerical_flux_func` to `entropy_stable_ns_operator`, it defaults to `entropy_stable_inviscid_flux_rusanov`.    
By internally defaulting this parameter, the multiphysics operator actually changes the expected default behavior.  If nothing is passed as `inviscid_numerical_flux_func` to the coupled operator, then it passes `invsicid_numerical_flux_func=inviscid_facial_flux_rusanov` regardless of whether we use the entropy stable or the standard NS …
> Pass through inviscid numerical flux func.

- mirgecom/simutil.py
Turns out we have two versions of `force_evaluation`, one in `utils` and one in `simutil`. I think the one in `utils` is the preferred implementation (it uses `freeze_thaw` instead of `thaw(freeze(...))`), so let's keep that one.
> Deprecate duplicate `force_evaluation`

- mirgecom/eos.py
- mirgecom/filter.py
- mirgecom/fluid.py
- mirgecom/gas_model.py
- mirgecom/transport.py
- test/test_av.py
- test/test_bc.py
- test/test_navierstokes.py
- test/test_symbolic.py
We seem to have some bugs in our tests that were uncovered by the changes in object array behavior in numpy 1.25. Specifically, in a few places we assert on the equality of `ConservedVars` objects:
```python
assert ff_bndry_state.cv == exp_ff_cv
```
which looks reasonable enough, but upon inspection:
```python
ff_bndry_state.cv == exp_ff_cv=ConservedVars(mass=DOFArray((cl.TaggableCLArray([[1],
[1]], dtype=int8),)), energy=DOFArray((cl.TaggableCLArray([[1],
[1]], dtype=int8),)), momentum=False, species_mass=array([], dtype=bool))
bool(ff_bndry_state.cv == exp_ff_cv)=True
```
i.e., `==` here is doing some strange things, and CV's boolean conversion is questionable. The discretization here is the boundary of a 1D mesh, so it looks like most of the components are doing elementwise equality, …
> Fix issues with `==` in tests and update to work with numpy 1.25

- setup.cfg
> ignore flake8-isort for now

- doc/conf.py
- doc/support/tools.rst
- examples/autoignition-mpi.py
- examples/combozzle-mpi.py
- examples/doublemach-mpi.py
- examples/doublemach_physical_av-mpi.py
- examples/heat-source-mpi.py
- examples/hotplate-mpi.py
- examples/lump-mpi.py
- examples/mixture-mpi.py
- examples/multiple-volumes-mpi.py
- examples/nsmix-mpi.py
- examples/poiseuille-local_dt-mpi.py
- examples/poiseuille-mpi.py
- examples/pulse-mpi.py
- examples/scalar-advdiff-mpi.py
- examples/scalar-lump-mpi.py
- examples/sod-mpi.py
- examples/thermally-coupled-mpi.py
- examples/vortex-mpi.py
- examples/wave-mpi.py
- examples/wave.py
- mirgecom/array_context.py
- mirgecom/simutil.py
> Production actx init

- mirgecom/multiphysics/thermally_coupled_fluid_wall.py
Looks like this was just left over from when the with-grad/without-grad cases were same function. It doesn't do anything in the without-grad case.
> Remove `wall_penalty_amount` argument from `add_interface_boundaries_no_grad`

- .ci-support/install.sh
- .github/workflows/ci.yaml
The doc CI error is likely caused by https://github.com/pocl/pocl/blob/569885d1a5e3b5abbaa40eb7a3061a51d35eada4/lib/CL/devices/common.c#L1198.
Using mambaforge for the CI install (like in emirge) massively speeds up installation time, from ~1hr to ~4 min.
> CI: use mambaforge, uninstall pocl before doc build

- .github/workflows/ci.yaml
> CI: Cancel prior runs when new run for same PR/branch is started

- test/test_fluid.py
> Fix errors from new flake8 version

- .github/workflows/ci.yaml
- examples/ablation-workshop-mpi.py
- examples/autoignition-mpi.py
- examples/combozzle-mpi.py
- examples/compare_lazy_solution.sh
- examples/doublemach-mpi.py
- examples/doublemach_physical_av-mpi.py
- examples/heat-source-mpi.py
- examples/hotplate-mpi.py
- examples/lump-mpi.py
- examples/mixture-mpi.py
- examples/multiple-volumes-mpi.py
- examples/nsmix-mpi.py
- examples/poiseuille-local_dt-mpi.py
- examples/poiseuille-mpi.py
- examples/pulse-mpi.py
- examples/scalar-advdiff-mpi.py
- examples/scalar-lump-mpi.py
- examples/sod-mpi.py
- examples/thermally-coupled-mpi.py
- examples/vortex-mpi.py
- examples/wave-mpi.py
- examples/wave.py
- mirgecom/array_context.py
- mirgecom/logging_quantities.py
- scripts/production-testing-env.sh
> add NumpyArrayContext support

- mirgecom/fluid.py
Internalizes the concept of join/split into the CV.  This eliminates the difference in CV array container implementation from production to main.
> Internalize split/join and remove the stale interface.

- mirgecom/mpi.py
- requirements.txt
Needs https://github.com/illinois-ceesd/emirge/pull/167
> use mpi4py git version for full pkl5 feature set

- mirgecom/simutil.py
- mirgecom/utils.py
- test/test_euler.py
- test/test_viscous.py
Match mostly cosmetic differences between main and production, adds an esdg entropy-to-conserved 
conversion util test to `test_euler.py`.
This change set trivially reduces the difference between production and main, but helps eliminate some merge conflicts in current developments (mostly Tulio's) when running production tests. 
> Slight changes to match production

- .rtd-env-py3.yml
Fixes the readthedocs build (https://readthedocs.org/projects/mirgecom/builds/23032216/)
> Fix RTD build

- examples/combozzle.py
- examples/pulse-tpe.py
- examples/pulse.py
- mirgecom/discretization.py
- mirgecom/simutil.py
- test/test_operators.py
This is the minimal lift that allows users/developers to use TPE easily in mirgecom drivers.  How-to use is demonstrated by the `combozzle` example, and a correctness test for TPE is added to the gradient test in `test_operators.py`.
> Add options for TPE and example, grad test.

- mirgecom/array_context.py
Adds options to `initialize_actx` reflecting the disabling of array context fallbacks and the override options that were added to meshmode/grudge. Also tweaked the implementation to try to simplify the logic a bit.
> Add override options for array context fallbacks

- examples/blasius.py
- examples/pulse-mixture.py
- mirgecom/boundary.py
- test/test_bc.py
- Update `species_mass_fractions` for non-mixture cases in RiemannBC.
- Allow either to prescribe or to extrapolate species in LinearOutflowBC; also, do not enforce the gradients to be zeros (over-specified).
- Extended LinearInflowBC and LinearOutflowBC to 1D
> Update Riemann and Linear BCs 

- mirgecom/artificial_viscosity.py
- mirgecom/discretization.py
> Fixes for meshmode/grudge compatibility

- mirgecom/array_context.py
- mirgecom/simutil.py
This 'fixes' the readthedocs build (see https://readthedocs.org/projects/mirgecom/builds/ for context)
> remove comm arg types to fix RTD build

- mirgecom/diffusion.py
- mirgecom/multiphysics/thermally_coupled_fluid_wall.py
- test/test_diffusion.py
- test/test_multiphysics.py
- Include normal projection of thermal conductivity for orthotropic cases.
- Add extra option to test in `test_multiphysics`
- ~Force thermal conductivity to be DOFArray sooner for diffusion operator.~
> Fix thermal interface for orthotropic cases

- doc/running/caching.rst
- mirgecom/mpi.py
XDG_CACHE_HOME support for MacOS has been added to loopy and pyopencl.
This partially reverts #1020.
> adjust MacOS kernel disk caching wrt XDG_CACHE_HOME

- mirgecom/gas_model.py
Allow limiter to optionally pass back p, T.  This can break things if the limiter passes back invalid p, T , but it is a performance bottleneck to disallow it when we trust that the driver-implemented limiter is returning the correct p, T.
(This is not adding a new behavior, it is optionally allowing the old behavior)
> Allow limiter to optionally pass back p,T

- examples/poiseuille-multispecies.py
- requirements.txt
- setup.cfg
> Use updated loopy

- examples/poiseuille-multispecies.py
- requirements.txt
- setup.cfg
Works around #1044, https://github.com/inducer/pyvisfile/issues/45
> Make pyvisfile non-editable

- mirgecom/diffusion.py
- mirgecom/euler.py
- mirgecom/operators.py
- requirements.txt
This change set updates mirgecom for compatibility with the new WADG implementation.  
> Use new WADG

- requirements.txt
- setup.py
> require mpi4py v4 instead of git version

- examples/run_examples.sh
- mirgecom/array_context.py
- mirgecom/logging_quantities.py
> DeviceMemoryUsage: add AMD support, use ProcessLogger for version.sh

- doc/running/device-selection.rst
`pytest_generate_tests_for_pyopencl_array_context` was removed in https://github.com/inducer/arraycontext/pull/278.
> Fix doc reference

- conda-env.yml
- examples/agitator.py
- examples/flow-over-cylinder.py
- mirgecom/discretization.py
- mirgecom/inviscid.py
- mirgecom/simutil.py
- requirements.txt
- setup.cfg
- test/mesh_data.py
- test/test_diffusion.py
- test/test_euler.py
- test/test_navierstokes.py
- test/test_operators.py
- test/test_overintegration.py
Meant to replace #1069.   This change set adds tests from the [Mengaldo paper on dealiasing](https://www.sciencedirect.com/science/article/pii/S0021999115004301#br0080) to verify and exercise overintegration in _mirgecom_.   The following are added or modified:
- Examples
- agitator.py: The variable coefficient advection setup from Mengaldo Sec. 4.1
- flow-over-cylinder.py: The subsonic inviscid flow over cylinder from Mengaldo Sec. 4.3.1
- Tests
- test_operators.py: Quadrature verification with Chebyshev polynomials
- test_overintegration.py: Variable coefficient overintegration verification from Mengaldo Sec. 4.1, Figure 7
- overintegration (and tpe) versions added to most flow, and operator tests as appropriate
- Support
- discretization.py: Fixed up choosing the proper *order* …
> Update support/testing for overintegration

- mirgecom/math.py
> document Expression-->ExpressionNode

- examples/mixture-tpe.py
- examples/mixture.py
- mirgecom/fluid.py
- mirgecom/wall_model.py
Avoids warnings of the type:
```
mirgecom/fluid.py:49: UserWarning: <class 'mirgecom.fluid.ConservedVars'> does not have __array_ufunc__ set. This will cause numpy to attempt broadcasting, in a way that is likely undesired. To avoid this, set __array_ufunc__ = None in <class 'mirgecom.fluid.ConservedVars'>.
```
> Add __array_ufunc__=None to relevant dataclasses

- mirgecom/mpi.py
- only print version on rank 0
- log library version
> better MPI version logging

- examples/wave.py
- mirgecom/limiter.py
- mirgecom/simutil.py
- setup.cfg
These errors are coming with the imminent update to latest inducer@main upstream pkgs.  Tried, but didn't figure out how to get around them instance-by-instance.
https://github.com/illinois-ceesd/mirgecom/actions/runs/12190311488/job/34010485460?pr=926
> Ignore these mypy errors

- setup.cfg
> Ignore missing logpyle imports

- mirgecom/mpi.py
grep has been treating mirgecom output files as binary recently. This seems to be the culprit.
> Remove null terminator from `MPI.Get_library_version` output
